language: python
python: 
  - "3.7"
  - "3.6"
  - "2.7"

before_install:
# Work around https://github.com/travis-ci/travis-ci/issues/7940
- export BOTO_CONFIG=/dev/null  

install:
- sudo apt-get update
- pip install .
- pip install -r requirements.txt
- pip install -r requirements_test.txt

script:
- py.test --cov srgutil tests
