language: python
python: 
  - "3.6"
  - "2.7"

before_install:
# Work around https://github.com/travis-ci/travis-ci/issues/7940
- export BOTO_CONFIG=/dev/null  

install:
# Update Travis
- sudo apt-get update
- pip install .
- pip install -r requirements.txt

script:
-     
- flake8 --max-line-length=100 srgutil tests || exit 1  # Fail if flake8 fails
- py.test --cov srgutil tests
